Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2018-03, with the labels that each got.

#1130 I1128 fix demand output
  cea/default.config
  cea/demand/demand_writers.py
Labels: Priority 1, bug, easy peasy

#1135 I1132 refix energy balance graph
  cea/demand/demand_writers.py
  cea/demand/hourly_procedure_heating_cooling_system_load.py
  cea/demand/latent_loads.py
  cea/demand/thermal_loads.py
  cea/plots/color_code.py
  cea/plots/demand/dashboard_district.py
  cea/plots/demand/energy_balance.py
Labels: Priority 1, bug

#1084 Optimization tool box for ArcGIS
  cea/interfaces/arcgis/CityEnergyAnalyst.py
  cea/interfaces/cli/cli.config
  cea/optimization/optimization_main.py
  cea/technologies/sewage_heat_exchanger.py
  environment.yml
Labels: Interface, Priority 1, enhancement

#1151 refactoring and re-adding final heating and cooling demand calc
  cea/demand/sensible_loads.py
  cea/demand/thermal_loads.py
Labels: bug, easy peasy, refactoring

#1160 I1076 revert to last working
  cea/default.config
  cea/demand/metamodel/nn_generator/input_matrix.py
  cea/demand/metamodel/nn_generator/input_prepare.py
  cea/demand/metamodel/nn_generator/nn_presampled_caller.py
  cea/demand/metamodel/nn_generator/nn_pretrainer_continue.py
  cea/demand/metamodel/nn_generator/nn_random_pipeline.py
  cea/demand/metamodel/nn_generator/nn_random_sampler.py
  cea/demand/metamodel/nn_generator/nn_settings.py
  cea/demand/metamodel/nn_generator/nn_test_sampler.py
  cea/demand/metamodel/nn_generator/nn_trainer.py
  cea/demand/metamodel/nn_generator/nn_trainer_continue.py
  cea/demand/metamodel/nn_generator/nn_trainer_estimate.py
  cea/demand/metamodel/nn_generator/nn_trainer_evaluate.py
  cea/demand/metamodel/nn_generator/readme.md
  cea/demand/metamodel/nn_generator/scaler_fit.py
  cea/demand/metamodel/nn_generator/scaler_sampler.py
Labels: Pushed, enhancement

#1167 Two versions of CEA logo and one MUSES
  logo/CEA-long.png
  logo/CEA.png
  logo/MuSES-acronym-NEW!.png
Labels: Priority 1
