Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2018-05, with the labels that each got.

#1287 i1192-i1286-clean-total-demands-fixed-comfort-plot
  cea/demand/demand_writers.py
  cea/plots/demand/comfort_chart.py
Labels: Priority 1, easy peasy

#1338 I1331 pv panels fail to run
  cea/default.config
  cea/interfaces/cli/cli.config
  cea/technologies/solar/photovoltaic.py
  cea/technologies/solar/photovoltaic_thermal.py
  cea/technologies/solar/solar_collector.py
  cea/utilities/solar_equations.py
Labels: Priority 1

#1348 Solves call from ArcGis
  cea/plots/plots_main.py
  cea/plots/thermal_networks/network_plot.py
Labels: bug, easy peasy

#1360 I1352 end use plots
  cea/demand/demand_writers.py
  cea/demand/thermal_loads.py
  cea/plots/demand/main.py
  cea/plots/demand/peak_load.py
  cea/plots/naming.csv
  cea/technologies/heatpumps.py
  cea/tests/test_calc_thermal_loads.config
Labels: Priority 1, enhancement

#1362 I1361 fix zero hot water demand
  cea/demand/hotwater_loads.py
  cea/demand/thermal_loads.py
Labels: Priority 1, bug

#1366 fixing issue
  cea/plots/demand/energy_demand.py
  cea/plots/demand/energy_use_intensity.py
  cea/plots/demand/load_duration_curve.py
  cea/plots/demand/main.py
  cea/plots/solar_potential/main.py
  cea/plots/solar_technology_potentials/main.py
Labels: Priority 1, bug

#1370 i1369 fix solar technology potential plot when there the total potential is zero
  cea/plots/solar_technology_potentials/all_tech_yearly.py
  cea/plots/solar_technology_potentials/pv_monthly.py
  cea/plots/solar_technology_potentials/pvt_monthly.py
  cea/plots/solar_technology_potentials/sc_monthly.py
Labels: Priority 1

#1356 Fix mobility issue again
  cea/analysis/lca/mobility.py
  cea/databases/CH/benchmarks/benchmark_2000W.xls
  cea/databases/SIN/benchmarks/benchmark_2000W.xls
Labels: easy peasy

#1379 1321 arcgis interface plotting of scenario comparison not interactive
  cea/config.py
  cea/default.config
  cea/interfaces/arcgis/CityEnergyAnalyst.py
  cea/interfaces/arcgis/install_toolbox.py
  cea/interfaces/arcgis/test.pyt
  cea/interfaces/cli/cli.config
  cea/plots/comparisons/main.py
Labels: Priority 1

#1383 fixed comfort plot: pass down locator and config, fix type
  cea/plots/demand/comfort_chart.py
  cea/plots/demand/main.py
Labels: Priority 1, bug

#1380 I1281 implement reduced time step option for thermal network matrix
  cea/constants.py
  cea/default.config
  cea/inputlocator.py
  cea/plots/thermal_networks/main.py
  cea/technologies/thermal_network/thermal_network_matrix.py
  cea/utilities/solar_equations.py
Labels: enhancement
