Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2018-11, with the labels that each got.

#1674 Fixing substation.calc_HEX_cooling loop with bhargava
  bin/test_substation_calc_hex_cooling.py
  cea/technologies/substation.py
  cea/tests/test_calc_thermal_loads.config
Labels: Must have, bug

#1697 1665 how to create pull request
  docs/how-to-contribute.rst
  docs/how-to-create-a-pull-request.rst
  docs/how-to-use-github.rst
  docs/pullrequest1.png
  docs/pullrequest2.png
  docs/pullrequest3.png
Labels: Must have

#1707 1706 Stochastic occupancy update
  cea/demand/demand_main.py
  cea/demand/occupancy_model.py
Labels: bug, easy peasy, enhancement

#1638 Create warning for RC-model breakdown
  cea/demand/building_properties.py
  cea/demand/constants.py
  cea/demand/rc_model_SIA.py
Labels: Must have, bug, documentation, enhancement
