Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2018-06, with the labels that each got.

#1432 IMPORTANT SOLAR RADIATION FIX!
  cea/resources/radiation_daysim/daysim_main.py
Labels: BIG NO NO, Priority 1, bug, enhancement, help wanted

#1447 Urgent fix for a h5py error that just showed up (failing jenkins tests)
  environment.yml
Labels: Priority 1, bug

#1456 Limit number of processes of multiprocessing
  cea/default.config
  cea/demand/demand_main.py
  cea/technologies/thermal_network/thermal_network_matrix.py
  cea/utilities/number_of_processes.py
Labels: easy peasy, enhancement

#1462 Updated LCA infrastructure database for Singapore
  cea/databases/SIN/lifecycle/LCA_infrastructure.xlsx
Labels: Priority 1, enhancement

#1474 update documentation with new names for solar collectors
  docs/cea-workflow-guide.rst
Labels: Priority 1

#1371 I1279 update pressure loss calculation in thermal network matrix
  cea/databases/CH/systems/supply_systems.xls
  cea/databases/SIN/systems/supply_systems.xls
  cea/inputlocator.py
  cea/plots/naming.csv
  cea/plots/plots_main.py
  cea/plots/thermal_networks/Supply_Return_Outdoor.py
  cea/plots/thermal_networks/energy_loss_bar.py
  cea/plots/thermal_networks/loss_curve.py
  cea/plots/thermal_networks/loss_duration_curve.py
  cea/plots/thermal_networks/main.py
  cea/plots/thermal_networks/network_plot.py
  cea/plots/thermal_networks/scenario_network_cost.py
  cea/technologies/constants.py
  cea/technologies/storage_tank.py
  cea/technologies/thermal_network/substation_matrix.py
  cea/technologies/thermal_network/thermal_network_matrix.py
Labels: enhancement

#1496 I1476 retrofit potential tool keyerror qhsf mwhyr
  cea/analysis/retrofit/retrofit_potential.py
Labels: bug

#1506 Speed up optimization (low hanging fruit)
  cea/technologies/chiller_absorption.py
  optimization_after.pstat
  optimization_before.pstat
Labels: Priority 1, refactoring

#1503 I1409 negative production from solar collectors
  cea/interfaces/cli/cli.config
  cea/plots/4D_plots_ArcGIS/radiation_total.py
  cea/resources/lake_potential.py
  cea/resources/sewage_heat_exchanger.py
  cea/technologies/solar/solar_collector.py
  docs/cea-workflow-guide.rst
  docs/modules/cea.technologies.rst
Labels: Priority 1

#1514 I773 operating cost of solar collectors is not calculated
  cea/__init__.py
  cea/optimization/preprocessing/decentralized_building_main.py
  cea/optimization/preprocessing/decentralized_buildings_cooling.py
  cea/technologies/chiller_absorption.py
Labels: Priority 1

#1520 I1501 fix occupancy and electricity
  cea/databases/SIN/archetypes/construction_properties.xlsx
  cea/databases/SIN/archetypes/occupancy_schedules.xlsx
  cea/databases/SIN/systems/envelope_systems.xls
  cea/demand/building_properties.py
  cea/demand/constants.py
  cea/demand/demand_main.py
  cea/demand/demand_writers.py
  cea/demand/occupancy_model.py
  cea/demand/thermal_loads.py
  cea/demand/ventilation_air_flows_simple.py
  cea/optimization/constants.py
  cea/technologies/heatpumps.py
  cea/tests/create_unittest_data.py
  cea/tests/test_calc_thermal_loads.config
  cea/tests/test_calc_thermal_loads.py
  cea/tests/test_schedules.config
Labels: Priority 1, bug, enhancement

#1517 Setting random seed for optimization
  cea/default.config
  cea/optimization/master/master_main.py
Labels: Priority 1, enhancement

#1521 I1164 solar collector temperatures
  cea/default.config
  cea/optimization/constants.py
  cea/optimization/master/cost_model.py
  cea/optimization/master/master_main.py
  cea/optimization/preprocessing/decentralized_buildings_cooling.py
  cea/plots/naming.csv
  cea/plots/optimization/cost_analysis_curve_decentralized.py
  cea/plots/optimization/main.py
  cea/technologies/chiller_absorption.py
  cea/technologies/solar/constants.py
  cea/technologies/solar/photovoltaic.py
  cea/technologies/solar/photovoltaic_thermal.py
  cea/technologies/solar/solar_collector.py
  cea/utilities/solar_equations.py
Labels: Priority 1

#1526 fixing heatmaps
  bin/cea-workflow.bat
  cea/plots/heatmaps.py
Labels: Priority 1, bug

#1528 fixes i1527
  cea/plots/demand/energy_balance.py
  cea/plots/demand/energy_use_intensity.py
  cea/plots/demand/main.py
  cea/plots/demand/peak_load.py
Labels: bug
