Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2018-04, with the labels that each got.

#1181 adding T4 back to domestic hot water emission system
  cea/databases/systems/emission_systems.xls
Labels: bug

#1178 Fix _get_region_specific_db_file
  cea/inputlocator.py
Labels: bug

#1189 removing faulty control from legacy
  cea/demand/control_heating_cooling_systems.py
  cea/tests/test_calc_thermal_loads.config
Labels: Priority 1, bug, enhancement

#1206 I 209 psychroplotting for cea
  cea/demand/demand_writers.py
  cea/plots/demand/comfort_chart.py
  cea/plots/demand/dashboard_district.py
Labels: Priority 1, enhancement

#1216 I 209 clean and documented comfort plot
  cea/plots/demand/comfort_chart.py
  cea/plots/demand/dashboard_district.py
Labels: documentation

#1228 I1169 integrating thermal network matrix with the new demand outputs
  cea/technologies/substation_matrix.py
  cea/technologies/thermal_network/thermal_network_matrix.py
Labels: Priority 1

#1172 I1138 plots cea arcgis
  cea/analysis/lca/embodied.py
  cea/analysis/lca/operation_costs.py
  cea/databases/CH/economics/supply_systems.xls
  cea/datamanagement/__init__.py
  cea/datamanagement/create_new_project.py
  cea/datamanagement/data_helper.py
  cea/default.config
  cea/demand/building_properties.py
  cea/demand/ventilation_air_flows_detailed.py
  cea/geometry/geometry_reader.py
  cea/geometry/network_layout/Readme.md
  cea/geometry/network_layout/__init__.py
  cea/geometry/network_layout/steiner_spanning_tree.py
  cea/inputlocator.py
  cea/interfaces/arcgis/CityEnergyAnalyst.py
  cea/interfaces/cli/cli.config
  cea/optimization/distribution/network_opt_main.py
  cea/plots/4D_plots_ArcGIS/sc_4D_plot.py
  cea/plots/comparisons/main.py
  cea/plots/demand/main.py
  cea/plots/life_cycle/main.py
  cea/plots/optimization/main.py
  cea/plots/plots_main.py
  cea/plots/solar_potential/dashboard_building.py
  cea/plots/solar_potential/dashboard_district.py
  cea/plots/solar_technology_potentials/all_tech_yearly.py
  cea/plots/solar_technology_potentials/main.py
  cea/plots/thermal_networks/main.py
  cea/technologies/thermal_network/network_layout/Readme.md
  cea/technologies/thermal_network/network_layout/__init__.py
  cea/technologies/thermal_network/network_layout/connectivity_potential.py
  cea/technologies/thermal_network/network_layout/main.py
  cea/technologies/thermal_network/network_layout/minimum_spanning_tree.py
  cea/technologies/thermal_network/network_layout/steiner_spanning_tree.py
  cea/technologies/thermal_network/network_layout/substations_location.py
  cea/tests/create_unittest_data.py
  cea/tests/dodo.py
  cea/tests/test_calc_thermal_loads.py
  cea/tests/test_schedules.py
  docs/cea-workflow-guide.rst
  docs/execution-time.xls
  docs/new-project-guide.rst
  environment.yml
  euler/README.md
Labels: Priority 1
