Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-06, with the labels that each got.

#2035 fixes building energy balance plots
  cea/plots/demand/energy_balance.py
Labels: bug, easy peasy

#2050 Improve description of variable `network-type`
  cea/default.config
Labels: Interface, Must have, documentation, enhancement

#2022 1949 3d visualization
  cea/interfaces/dashboard/inputs/routes.py
  cea/interfaces/dashboard/inputs/static/css/deckgl.css
  cea/interfaces/dashboard/inputs/static/js/inputs.js
  cea/interfaces/dashboard/inputs/static/js/map.js
  cea/interfaces/dashboard/inputs/templates/table.html
Labels: Must have

#2034 I1932 process schedules for lab
  cea/__init__.py
  cea/databases/SG/archetypes/occupancy_schedules.xlsx
  cea/datamanagement/data_helper.py
  cea/datamanagement/databases_verification.py
  cea/demand/occupancy_model.py
Labels: bug

#2052 Thermal network simulation config file
  cea/technologies/thermal_network/thermal_network.py
  cea/technologies/thermal_network/thermal_network_optimization.py
  setup.py
Labels: bug

#2059 Remove brackets from `sheet_name` instances
  cea/resources/geothermal.py
  cea/technologies/thermal_network/substation_matrix.py
  cea/technologies/thermal_network/thermal_network.py
  setup.py
Labels: bug

#2109 2096 error on creating energy use intensity plot
  cea/interfaces/dashboard/plots/routes.py
  cea/plots/base.py
  cea/plots/demand/__init__.py
  cea/plots/demand/comfort_chart.py
  cea/plots/demand/energy_use_intensity.py
  cea/plots/demand/heating_reset_schedule.py
Labels: Must have
