Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-04, with the labels that each got.

#1867 Plot cache for dashboard
  cea/config.py
  cea/interfaces/dashboard/dashboard.py
  cea/interfaces/dashboard/plots/routes.py
  cea/interfaces/dashboard/project/routes.py
  cea/plots/__init__.py
  cea/plots/base.py
  cea/plots/cache.py
  cea/plots/categories.py
  cea/plots/demand/__init__.py
  cea/plots/demand/comfort_chart.py
  cea/plots/demand/energy_balance.py
  cea/plots/demand/energy_demand.py
  cea/plots/demand/energy_supply.py
  cea/plots/demand/energy_supply_intensity.py
  cea/plots/demand/energy_use_intensity.py
  cea/plots/demand/heating_reset_schedule.py
  cea/plots/demand/load_curve.py
  cea/plots/demand/load_curve_supply.py
  cea/plots/demand/load_duration_curve.py
  cea/plots/demand/load_duration_curve_supply.py
  cea/plots/demand/peak_load.py
  cea/plots/demand/peak_load_supply.py
  cea/plots/optimization/__init__.py
  cea/plots/optimization/centralized_costs_per_generation_unit.py
  cea/plots/optimization/cost_analysis_centralized_system.py
  cea/plots/optimization/pareto_capacity_installed.py
  cea/plots/optimization/pareto_curve.py
Labels: Must have, enhancement

#1885 Restrict length of year to 8760 hours
  cea/demand/calibration/subset_calibrator/sus_calibrator.py
  cea/demand/control_heating_cooling_systems.py
  cea/demand/datacenter_loads.py
  cea/demand/demand_main.py
  cea/demand/electrical_loads.py
  cea/demand/hotwater_loads.py
  cea/demand/metamodel/nn_generator/input_matrix.py
  cea/demand/occupancy_model.py
  cea/demand/refrigeration_loads.py
  cea/demand/sensible_loads.py
  cea/demand/set_point_from_predefined_file.py
  cea/demand/thermal_loads.py
  cea/demand/ventilation_air_flows_simple.py
  cea/optimization/distribution/network_opt_main.py
  cea/optimization/flexibility_model/model_building/building_main.py
  cea/optimization/individual_evaluation/individual_cooling_main.py
  cea/optimization/lca_calculations.py
  cea/optimization/master/summarize_network.py
  cea/optimization/preprocessing/decentralized_buildings_cooling.py
  cea/optimization/preprocessing/decentralized_buildings_heating.py
  cea/optimization/preprocessing/preprocessing_main.py
  cea/optimization/preprocessing/processheat.py
  cea/optimization/slave/cooling_main.py
  cea/optimization/slave/electricity_main.py
  cea/optimization/slave/heating_main.py
  cea/optimization/slave/natural_gas_main.py
  cea/optimization/slave/seasonal_storage/Import_Network_Data_functions.py
  cea/optimization/slave/seasonal_storage/design_operation.py
  cea/plots/4D_plots_ArcGIS/demand_4D_plot.py
  cea/plots/4D_plots_ArcGIS/pv_4D_plot.py
  cea/plots/4D_plots_ArcGIS/pvt_4D_plot.py
  cea/plots/4D_plots_ArcGIS/radiation_4D_plot.py
  cea/plots/4D_plots_ArcGIS/radiation_total.py
  cea/plots/4D_plots_ArcGIS/sc_4D_plot.py
  cea/plots/demand/load_duration_curve.py
  cea/plots/demand/load_duration_curve_supply.py
  cea/plots/old/graphs_optimization.py
  cea/plots/thermal_networks/loss_duration_curve.py
  cea/plots/thermal_networks/main.py
  cea/resources/geothermal.py
  cea/resources/lake_potential.py
  cea/technologies/solar/photovoltaic.py
  cea/technologies/solar/photovoltaic_thermal.py
  cea/technologies/solar/solar_collector.py
  cea/technologies/substation.py
  cea/tests/test_schedules.py
  cea/utilities/epwreader.py
  cea/utilities/reporting.py
  cea/utilities/solar_equations.py
  legacy/radiation_arcgis/calculate_incident_radiation.py
Labels: bug

#1887 Fix typo in `datacenter_loads`
  cea/demand/datacenter_loads.py
Labels: bug

#1906 Add weather file for Dutch case study
  cea/databases/weather/Lelystad.epw
Labels: Must have, enhancement

#1900 Shift case studies below sea level to an elevation of 1 meter
  cea/demand/control_heating_cooling_systems.py
  cea/resources/radiation_daysim/geometry_generator.py
Labels: enhancement

#1899 Make solar plots run if only one technology is selected
  cea/plots/solar_technology_potentials/all_tech_yearly.py
  cea/plots/solar_technology_potentials/main.py
Labels: bug
