Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-10, with the labels that each got.

#2365 Ventilation code cleanup
  cea/demand/constants.py
  cea/demand/ventilation_air_flows_detailed.py
Labels: documentation, enhancement

#2378 I2204b temperature setpoints finish
  cea/databases/CH/archetypes/occupancy_schedules.xlsx
  cea/tests/test_calc_thermal_loads.config
Labels: bug, enhancement

#2407 Update LCA_infrastructure.xlsx
  cea/databases/SG/lifecycle/LCA_infrastructure.xlsx
Labels: Must have, bug
