Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-01, with the labels that each got.

#1756 Fix issue with `mcpcdata_sys_kWperC`
  cea/technologies/thermal_network/substation_matrix.py
Labels: bug

#1775 Add missing file outputs from representative week method
  cea/technologies/thermal_network/thermal_network_matrix.py
Labels: bug, easy peasy

#1778 I 1767 fix longwave radiation bug
  cea/demand/sensible_loads.py
  cea/tests/create_unittest_data.py
  cea/tests/test_calc_thermal_loads.config
Labels: Must have, bug, documentation
