Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-11, with the labels that each got.

#2433 Update geometry_generator.py
  cea/resources/radiation_daysim/geometry_generator.py
Labels: bug

#2431 Update scripts.yml
  cea/scripts.yml
Labels: bug, enhancement

#2452 Update epwreader.py
  cea/utilities/epwreader.py
Labels: bug

#2448 Ventilation to avoid unrealistically high temperatures during heating season
  cea/constants.py
  cea/databases/CH/archetypes/construction_properties.xlsx
  cea/demand/constants.py
  cea/demand/control_ventilation_systems.py
  cea/demand/demand_main.py
  cea/demand/hourly_procedure_heating_cooling_system_load.py
  cea/demand/schedule_maker/schedule_maker.py
  cea/demand/thermal_loads.py
  cea/tests/create_unittest_data.py
  cea/tests/test_calc_thermal_loads.config
Labels: enhancement

#2475 Window to wall ratio and envelope properties
  cea/demand/building_properties.py
Labels: bug, enhancement
