Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-02, with the labels that each got.

#1599 Network optimization
  cea/databases/CH/systems/supply_systems.xls
  cea/databases/SG/systems/emission_systems.xls
  cea/databases/SG/systems/supply_systems.xls
  cea/default.config
  cea/inputlocator.py
  cea/plots/supply_system/main.py
  cea/plots/thermal_networks/main.py
  cea/technologies/chiller_vapor_compression.py
  cea/technologies/constants.py
  cea/technologies/cooling_tower.py
  cea/technologies/heat_exchangers.py
  cea/technologies/pumps.py
  cea/technologies/thermal_network/network_layout/main.py
  cea/technologies/thermal_network/network_layout/steiner_spanning_tree.py
  cea/technologies/thermal_network/substation_matrix.py
  cea/technologies/thermal_network/thermal_network_costs.py
  cea/technologies/thermal_network/thermal_network_matrix.py
  cea/technologies/thermal_network/thermal_network_optimization.py
  docs/How-to-document-cea.rst
  docs/how-to-prepare-inputs-for-network-simulation.rst
  docs/how-to-run-thermal-network-optimization.rst
  docs/tutorials.rst
Labels: Epic, Must have, enhancement

#1789 1780 thermal network matrix rename
  cea/optimization/individual_evaluation/individual_cooling_main.py
  cea/optimization/master/cost_model.py
  cea/optimization/optimization_main.py
  cea/optimization/preprocessing/decentralized_buildings_cooling.py
  cea/optimization/slave/cooling_main.py
  cea/plots/supply_system/main.py
  cea/scripts.yml
  cea/technologies/thermal_network/substation_matrix.py
  cea/technologies/thermal_network/thermal_network.py
  cea/technologies/thermal_network/thermal_network_matrix.py
  cea/technologies/thermal_network/thermal_network_optimization.py
  cea/tests/dodo.py
  docs/how-to-add-a-new-script-to-the-cea.rst
  docs/how-to-document-cea.rst
  legacy/thermal_networks/__init__.py
  legacy/thermal_networks/thermal_network.py
Labels: Should have

#1787 1069 document input output variables
  cea/tests/trace_inputlocator.py
  cea/tests/trace_inputlocator.template.gv
  docs/script_dependencies/data-helper.gv
  docs/script_dependencies/data-helper.yml
  docs/script_dependencies/data-helper_radiation-daysim_demand.gv
  docs/script_dependencies/data-helper_radiation-daysim_demand.yml
  docs/script_dependencies/demand.gv
  docs/script_dependencies/demand.yml
  docs/script_dependencies/emissions.gv
  docs/script_dependencies/emissions.yml
  docs/script_dependencies/photovoltaic-thermal.gv
  docs/script_dependencies/photovoltaic-thermal.yml
  docs/script_dependencies/photovoltaic.gv
  docs/script_dependencies/photovoltaic.yml
  docs/script_dependencies/radiation-daysim.gv
  docs/script_dependencies/radiation-daysim.yml
  docs/script_dependencies/script_dependencies_gen.py
  docs/script_dependencies/script_dependencies_template.rst
  docs/script_dependencies/solar-collector.gv
  docs/script_dependencies/solar-collector.yml
  docs/script_dependencies/thermal-network-matrix.gv
  docs/script_dependencies/thermal-network-matrix.yml
  docs/tutorials.rst
  docs/what-are-the-cea-scripts.rst
Labels: documentation

#1793 Correct archetypal values of Es for PARKING and COOLROOM
  cea/databases/CH/archetypes/construction_properties.xlsx
  cea/tests/test_schedules.py
Labels: bug, easy peasy
