Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2019-05, with the labels that each got.

#1905 Add floor cooling to CEA systems
  cea/databases/CH/systems/emission_systems.xls
  cea/databases/SG/systems/emission_systems.xls
  cea/demand/control_heating_cooling_systems.py
  cea/demand/hourly_procedure_heating_cooling_system_load.py
  cea/demand/rc_model_SIA.py
  cea/demand/sensible_loads.py
Labels: Must have, enhancement

#1903 Make each function that has occupants have a minimum of one occupant
  cea/demand/occupancy_model.py
Labels: Must have, enhancement

#2000 I1950 remove arcgis radiation
  cea/default.config
  cea/demand/building_properties.py
  cea/demand/calibration/subset_calibrator/sus_calibrator.py
  cea/demand/demand_main.py
  cea/demand/metamodel/nn_generator/input_matrix.py
  cea/demand/metamodel/nn_generator/input_prepare.py
  cea/demand/metamodel/nn_generator/nn_random_pipeline.py
  cea/demand/metamodel/nn_generator/nn_random_sampler.py
  cea/demand/metamodel/nn_generator/nn_test_sampler.py
  cea/demand/metamodel/nn_generator/nn_trainer_estimate.py
  cea/demand/metamodel/nn_generator/nn_trainer_evaluate.py
  cea/demand/metamodel/nn_generator/scaler_sampler.py
  cea/demand/occupancy_model.py
  cea/tests/cea.config
  cea/tests/create_unittest_data.py
  cea/tests/dodo.py
  cea/tests/test_calc_thermal_loads.py
  cea/tests/test_check_for_radiation_input_in_demand_script.py
  cea/tests/test_schedules.py
Labels: enhancement, refactoring

#2009 1985 add life cycle plots to the dashboard
  cea/interfaces/cli/cli.py
  cea/plots/base.py
  cea/plots/demand/__init__.py
  cea/plots/life_cycle/__init__.py
  cea/plots/life_cycle/emissions.py
  cea/plots/life_cycle/emissions_intensity.py
  cea/plots/life_cycle/operation_costs.py
  cea/plots/life_cycle/primary_energy.py
  cea/plots/life_cycle/primary_energy_intensity.py
  cea/plots/solar_potential/__init__.py
  cea/plots/solar_potential/solar_radiation_curve.py
Labels: Must have

#1994 Missing cool room and server room loads
  cea/demand/building_properties.py
  cea/demand/constants.py
  cea/demand/datacenter_loads.py
  cea/demand/occupancy_model.py
  cea/demand/refrigeration_loads.py
  cea/demand/thermal_loads.py
  cea/interfaces/dashboard/inputs/routes.py
  cea/tests/test_calc_thermal_loads.config
Labels: bug

#2028 Steiner tree and buildings with no demand
  cea/default.config
  cea/technologies/network_layout/main.py
  cea/technologies/network_layout/steiner_spanning_tree.py
  cea/technologies/network_layout/substations_location.py
Labels: bug, enhancement
