Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2020-02, with the labels that each got.

#2545 Fixed typo in a variable name
  cea/default.config
  cea/technologies/thermal_network/simplified_thermal_network.py
Labels: easy peasy

#2574 Use consistent input locator method in building_properties.py
  cea/demand/building_properties.py
Labels: bug

#2571 fix skytemp
  cea/constants.py
  cea/demand/sensible_loads.py
  cea/tests/test_calc_thermal_loads.config
  cea/utilities/epwreader.py
  cea/utilities/physics.py
Labels: Must have, bug
