Repository architecture-building-systems/CityEnergyAnalyst, pull requests merged in 2024-12, with the labels that each got.

#3720 now summary also includes irradiation
  cea/default.config
  cea/import_export/result_summary.py
Labels: priority-must-have, feature-new

#3731 Pv analytics by building
  cea/import_export/result_summary.py
  cea/inputlocator.py
Labels: priority-must-have, feature-new

#3732 Update building_properties.py
  cea/demand/building_properties.py
Labels: is-bug, priority-must-have, feature-demand

#3735 merge architecture to selected buildings
  cea/default.config
  cea/import_export/result_summary.py
Labels: is-bug, priority-must-have, feature-new

#3739 Update daysim linux binaries
  Dockerfile
  cea/resources/radiation/bin/linux/ds_illum
  cea/resources/radiation/bin/linux/epw2wea
  cea/resources/radiation/bin/linux/gen_dc
  cea/resources/radiation/bin/linux/oconv
  cea/resources/radiation/bin/linux/radfiles2daysim
  cea/resources/radiation/bin/linux/rtrace_dc
Labels: is-bug, priority-must-have

#3741 update gh script to handle shp with Z coord
  cea/scripts.yml
Labels: is-bug, priority-must-have
